### ISSUE TITLE
Blob to base64 support in ion-text

### ISSUE THREAD

**Issue by bglowney** [amzn/ion-js#199]
Please support displaying blobs as base64.

These lines prevent this currently:

https://github.com/amzn/ion-js/blob/master/src/IonTextReader.ts#L210
https://github.com/amzn/ion-js/blob/master/src/IonTextReader.ts#L237

**Comment by wesboyt** [comment]
To support this we will need to make one off changes that will be burned during a v3 release:

textparser needs bugfixes from development:
https://github.com/amzn/ion-js/blob/master/src/IonParserTextRaw.ts#L944
https://github.com/amzn/ion-js/blob/development/src/IonParserTextRaw.ts#L944

textreader will need to pull bytevalue/value and change the type to number[]:
https://github.com/amzn/ion-js/blob/development/src/IonTextReader.ts#L237
https://github.com/amzn/ion-js/blob/master/src/IonTextReader.ts#L237

iontextwriter will need to pull writeBlob from development and alter the api types
https://github.com/amzn/ion-js/blob/master/src/IonTextWriter.ts#L62
https://github.com/amzn/ion-js/blob/development/src/IonTextWriter.ts#L53

tobase64 and frombase64 in development will need to produce number[] instead of uint8array
https://github.com/amzn/ion-js/blob/master/src/IonText.ts#L190
https://github.com/amzn/ion-js/blob/development/src/IonText.ts#L185

we will need unit tests reviewed and eventstream will need some patches:
https://github.com/amzn/ion-js/blob/master/src/IonEvent.ts#L362
https://github.com/amzn/ion-js/blob/development/src/IonEvent.ts#L347

**Comment by wesboyt** [comment]
done, available in blobsupport branch.
