### ISSUE TITLE
Decimal Compare

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#295]
Currently Decimal compare is not complying with the equivalence function used in ion java.
for instance 2.1 and 2.10 evaluate as equal while java would evaluate them as unequal.
https://github.com/amzn/ion-js/blob/development/src/IonDecimal.ts#L139
https://github.com/amzn/ion-js/blob/development/tests/unit/IonDecimalTest.js#L67

spec:
http://speleotrove.com/decimal/daops.html#refnumco

http://speleotrove.com/decimal/damisc.html#refcotot

**Comment by wesboyt** [comment]
We just need to add a coefficient size check when two values evaluate equivalent in the last case of the function.

**Comment by pbcornell** [comment]
To clarify:  the Ion spec doesn't define expected behavior for a compareTo method.  ion-java's `Decimal.compareTo()` defers to `java.math.BigDecimal.compareTo()`, which ignores precision and negative zeros (see [javadoc for Decimal.equals()](https://github.com/amzn/ion-java/blob/d5939190808b815ec940ef5d45db0d39e9c3fb63/src/com/amazon/ion/Decimal.java#L172)).

In contrast, `Decimal.equals()` implements decimal equivalence as defined by the Ion spec, which requires precision to match, and treats 0 and -0 as non-equal values.

I'd suggest we follow that pattern in ion-js.

**Comment by pbcornell** [comment]
Resolved by #314; closing.
