### ISSUE TITLE
Developer friendly interfaces for reading ion objects.

### ISSUE THREAD

**Issue by saumehta9** [amzn/ion-js#531]
**Problem**: The interfaces for writing/reading ion are quite verbose. http://amzn.github.io/ion-docs/guides/cookbook.html#reading-and-writing-ion-data

Extracting a single field requires walking the document through functions like next(), stepIn().

for eg: 

Reading with ion-js 

```
let ion = require('ion-js');

let reader = ion.makeReader('{hello: "world"}');
reader.next();                         // position the reader at the first value, a struct
reader.stepIn();                       // step into the struct
reader.next();                         // position the reader at the first value in the struct
let fieldName = reader.fieldName();    // retrieve the current value's field name
let value = reader.stringValue();      // retrieve the current value's string value
reader.stepOut();                      // step out of the struct
console.log(value);  // prints: world
```

Whereas if we compare this to ion python : 

```
import amazon.ion.simpleion as ion

obj = ion.loads('{hello: world}')
print(obj['hello'].text)                            //prints world
```

The ion python library has much easier to use/understand interfaces.

Feature Request:
Developer friendly and less verbose interfaces to read/write ION objects.

Something like: 

```
let ionObject = ion.loads('{hello: "world"}');

console.log(ionObject['hello'].text);  // prints: world
```

**Comment by jmagnuss** [comment]
+1 was hoping to get Typescript objects out that I could manipulate or return in an API, instead I have to walk a dom tree. Working on adapting the pretty writer to output JSON but it's risky...

**Comment by wesboyt** [comment]
@jmagnuss do you need to manipulate it? generally wed like to make the sequence of objects immutable due to the added api risk and decreased perf of allowing users to manipulate its symboltable context.

**Comment by zslayton** [comment]
We're looking into what it would take to offer a straightforward `load()` API to get a JS Object value from a given `Reader`. I'll update this issue when we have more details.

**Comment by jmagnuss** [comment]
I don't need to manipulate it, I'm working on a REST API that manages records in QLDB.

Here's my quick solution last night: https://gist.github.com/jmagnuss/419db1c4891b5aa7f79a40e4cf8e9a4a
I was going to toss it up as a module this morning, but if we can natively support down-converting to JSON and Objects in the official library, that would be ideal.

**Comment by doberenz** [comment]
I ran into a similar issue working with QLDB. I have a quick and dirty object implementation, but I haven't set up all the tests I'd like to have on it yet. I'll make sure I push it up to my fork today. If anyone wants to see the basic idea, here's a gist with relatively recent code - https://gist.github.com/doberenz/01927f18a1c785c58ab0536b3987a6ee

**Comment by fuwjax** [comment]
I have the reader side of the tests passing at https://github.com/fuwjax/ion-js. I had some difficulty getting it to build on my work laptop, "fuwjax" is my personal GitHub account.

The basic premise, construct a Reader and pass it to IonObject.values(). That will return an iterator over IonObject instances. Those instances are a bit clumsy, as you have to keep calling .value and casting the result to a type. The value objects have .asSomething properties to avoid the cast, but you'll still have to cast to the value object itself.

At the very least, the resulting object will give you a .json property that you could parse back to a json object, that should at least obey the rules from the ion spec. I can add an .asNative property to save the hassle of parsing, but this is starting to feel like more baling wire and duct tape.

The issue I was running into was that to do an update in QLDB, I wanted to fetch an object, change it a bit and resubmit the object. That meant being able to swap from ion to json and back to ion, preferably with the same mutable object. Instead, I think there is some value in treating the objects as immutable and having a builder pattern for creating an ion object. That way a reader could return simple javascript objects without the type hierarchy, and when creating an ion object you'd have a literate syntax instead of an object/array json model.

**Comment by zslayton** [comment]
Hi all! The next release will include [the new DOM API](https://github.com/amzn/ion-js/blob/master/src/dom/README.md), which aims to address this issue.

**Comment by zslayton** [comment]
[Version 4.0.0](https://github.com/amzn/ion-js/releases/tag/v4.0.0) has been released.
