### ISSUE TITLE
ion-js v4.0.0 npm install missing jsbi

### ISSUE THREAD

**Issue by jfuehner** [amzn/ion-js#600]
Hi! When I was installing ion-js v4.0.0 npm complained that it was missing the dependency `jsbi`. I was able to workaround the error by explicitly installing `jsbi` within my own project.

**Comment by zslayton** [comment]
As of version `4.0.0`, `jsbi` is a [peer dependency](https://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html), allowing/requiring users to bring their own version of the library.

This behavior is intentional, so I'm going to close this issue. Feel free to re-open if you have other questions or I've misunderstood something.
