### ISSUE TITLE
Make the dom types ADT-compatible

### ISSUE THREAD

**Issue by fnmdx111** [amzn/ion-js#678]
It would be nice to be able to differentiate `dom.Value` objects by employing the technique of algebraic data type. For example, right now to obtain a list value from a `dom.Value` value, you could do,

```typescript
const xs = maybeList.as(dom.List);
if (xs !== null) {
    doSomethingWithList(xs);
}
```

but it would be nice to utilize ADT so that when you check against it's discriminating field, TypeScript will automatically narrow down the type,

```typescript
function isList(v: dom.Value): boolean {
    return v.type === "list";
}

if (isList(xs)) {
    doSomethingWithList(xs); // TS automatically narrows down the type from dom.Value to dom.List;
}
```

This makes the following code possible:

```typescript
function traverseIonValue(v: dom.Value) {
    switch (v.type) {
        case "list":
            // v is now narrowed down to dom.List by the compiler
        case "struct":
            // v is now narrowed down to dom.Struct by the compiler
        ...
    }
}
```

I'd love to work on a PR if you think this is something you'd like in the library. Thanks.

**Comment by zslayton** [comment]
This would be nice functionality to have! Typescript didn't have this feature back when `ion-js` v4 was released.

I believe the reason it's not currently supported is that the DOM types have to use mixins in order to be considered descendants of multiple parent classes. An `ion.dom.Integer` needs to be a subclass of `dom.Value` _and_ `Number`, which means the class can't just `extend global.Number`. Mixins allow us to use `instanceof` and method overrides as expected for both.

Is there a way to add support for type narrowing while using mixins?

**Comment by fnmdx111** [comment]
I did some experiments last night and I don't think I have enough expertise to make TypeScript do what I want it to do. I tried adding a readonly field in the Value interface, then creating a union type out of the concrete sub types (e.g. Integer) so that the union type share the same discriminating field. But using the union type did not result in type narrowing (even with latest TS compiler).

**Comment by fnmdx111** [comment]
Closing since there's no clear way forward.
