### ISSUE TITLE
DOM Decimal: super constructor call needs update (and looks buggy)

### ISSUE THREAD

**Issue by jakobkummerow** [amzn/ion-js#700]
See [here](https://github.com/amzn/ion-js/blob/ada4439df48b0467c26ce6487bed78f050716360/src/dom/Decimal.ts#L34):
```
  constructor(value: ion.Decimal, annotations: string[] = []) {
    super(...[value.getCoefficient(), value.getExponent(), value.isNegative()]);
    this._decimalValue = value;
    this._numberValue = value.numberValue();
    this._setAnnotations(annotations);
  }
```
Since `class Decimal extends Value(Number, ...)`, `super` is effectively the plain JavaScript `Number` constructor. There are two issues here:

(1) `value.getCoefficient()` returns a JSBI instance. Newer versions of JSBI disallow `new Number(some_jsbi)` constructor calls. The supported alternative is to use `JSBI.toNumber(some_jsbi)` instead. This came up at https://github.com/GoogleChromeLabs/jsbi/issues/85.
(Background: this change was made in an effort to disallow invalid conversions that wouldn't work any more once JSBI is compiled away to native BigInts. `Number(42n)` is fine, but `+42n` is not; so JSBI now disallows `+some_jsbi`, which as "collateral damage" also disallows `Number(some_jsbi)`. FWIW, JSBI's [documentation](https://github.com/GoogleChromeLabs/jsbi#how) has always recommended to use `JSBI.toNumber`, the fact that `Number(some_jsbi)` also worked was accidental.)

(2) The `Number` constructor takes only one argument. Calling it with three arguments looks like a bug, as `value.getExponent()` and `value.isNegative()` will just be ignored. (Presumably the value passed to the super ctor is never used for anything, which would explain why this hasn't caused issues so far?)

I would suggest to fix both issues at once by changing the super call to `super(...[value.numberValue()])`. (Or, more simply, `super(value.numberValue())`. Or, if my suspicion is correct that the value is indeed never used, just drop the super call entirely.)

Apologies in advance if I've misunderstood anything.

**Comment by popematt** [comment]
Thanks for bringing this to our attention.

We can't drop the `super` call entirely because TypeScript requires a `super` call in the constructor of a derived class.

I agree with your observation about calling the `Number` constructor with 3 args—it does look like a mistake. I tried replacing the existing super call with `super(value.numberValue())` and our test suite still passes, so I think it's probably a safe change to make. However, it is wisest to try to understand the prior decision before we go and change it, so we're going to dig around for some context to see if we can understand why it was done that way.

Is that enough to unblock you (for now)? I tried updating our dependencies to use JSBI 4.1, but it seems like some of our tests are using the prohibited functions, and it seems like another side-effect of of the change you mentioned is that JSBI can no longer be coerced to a string. For example, this line no longer works when using JSBI 4.1. https://github.com/amzn/ion-js/blob/832219bff77a9deb6cef6bf7746ba05b0925a525/src/events/IonEvent.ts#L471

We can work around this by explicitly invoking `toString()`, but is this expected?

**Comment by jakobkummerow** [comment]
Thanks for following up!

> Will that be enough to unblock you (for now)?

It's the only issue I've heard of.

> We can work around this by explicitly invoking `toString()`, but is this expected?

I wasn't aware of it, but it makes sense: the `+` [binary operator](https://tc39.es/ecma262/#sec-applystringornumericbinaryoperator) calls `ToPrimitive` without a type hint, and by default `valueOf` is tried before `toString`, so if the former throws then the latter doesn't get called at all. Calling `toString()` manually is the obvious workaround. (I'm not happy about the lack of ergonomics of having to spell that out, but I don't see a better way.)
